CREATE DATABASE IF NOT EXISTS ficha_medica;
USE ficha_medica;

CREATE TABLE IF NOT EXISTS paciente (
  rut VARCHAR(20) PRIMARY KEY,
  nombres VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  direccion VARCHAR(150) NOT NULL,
  ciudad VARCHAR(100) NOT NULL,
  telefono VARCHAR(30) NOT NULL,
  email VARCHAR(150) NOT NULL,
  fecha_nacimiento DATE NOT NULL,
  estado_civil VARCHAR(30) NOT NULL,
  comentarios TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);